apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: k8s   # required field for kubernetes.io/basic-auth
  password: magic # required field for kubernetes.io/basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
type: Opaque
stringData:
  connection_string: SERVER=moo;USER=boo;PARAM=foo;
data:
  usernameAlt: azhz  
  passwordAlt: bWFnaWM=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      envFrom: # import all with original names
      - secretRef:
          name: secret-basic-auth
      env:
        - name: DB 
          valueFrom:
            secretKeyRef: # map specific to env var 
              name: secret-demo 
              key: connection_string
