apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "DepWithPV.fullname" . }}
  labels:
    {{- include "DepWithPV.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "DepWithPV.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "DepWithPV.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: {{ .Chart.Name }}-volume
        persistentVolumeClaim:
          claimName: {{ .Values.storage.name }}-pvc
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: {{ .Chart.Name }}-volume
            mountPath: {{ .Values.deployment.mountPath }}
            readOnly: true