apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.name }}-pv
  labels:
    {{- include "DepWithPV.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.storage.storageClassName }}
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - {{ .Values.storage.accessModes }}
  hostPath:
    path: {{ .Values.storage.hostPath }} 