apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-with-pv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
      - name: pages-from-volume #regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?'
        persistentVolumeClaim:
          claimName: pv-claim
      containers:
      - name: my-app1
        image: nginx
        resources:
          requests: 
            memory: "4Mi"
            cpu: "2m"
          limits:
            memory: "20Mi"
            cpu: "30m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pages-from-volume #regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?'
          mountPath: "/usr/share/nginx/html"  #default nginx pages content dir
          readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  storageClassName: hostpath #docker default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5000Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  storageClassName: hostpath #docker default
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: "/run/desktop/mnt/host/c/www" 
      # For windows prefix is /run/desktop/mnt/host/<disk-letter>/<local-path-to-folder> 
    
      #path: "/mnt/data" 
      # For linux should be trivial
      
      #path: "/tmp" 
      # For Mac - Filesharing https://julien-chen.medium.com/k8s-how-to-mount-local-directory-persistent-volume-to-kubernetes-pods-of-docker-desktop-for-mac-b72f3ca6b0dd