apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-deployment
  annotations:
    kubernetes.io/change-cause: "Upgrade to v2"
  labels:
    app-revision: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollout-app
  template:
    metadata:
      labels:
        app: rollout-app
        app-revision: v2
    spec:
      containers:
      - name: rollout-app
        image: ealen/echo-server
        resources:
          requests: 
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ECHO_TEXT
          value: That's all folks!